// Generated by gencpp from file ros_tengine/FaceObject.msg
// DO NOT EDIT!


#ifndef ROS_TENGINE_MESSAGE_FACEOBJECT_H
#define ROS_TENGINE_MESSAGE_FACEOBJECT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ros_tengine/Rectangle.h>
#include <ros_tengine/Vector2D.h>

namespace ros_tengine
{
template <class ContainerAllocator>
struct FaceObject_
{
  typedef FaceObject_<ContainerAllocator> Type;

  FaceObject_()
    : header()
    , boundingbox()
    , landmark()
    , probability(0.0)  {
    }
  FaceObject_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , boundingbox(_alloc)
    , landmark(_alloc)
    , probability(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::ros_tengine::Rectangle_<ContainerAllocator>  _boundingbox_type;
  _boundingbox_type boundingbox;

   typedef std::vector< ::ros_tengine::Vector2D_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::ros_tengine::Vector2D_<ContainerAllocator> >> _landmark_type;
  _landmark_type landmark;

   typedef float _probability_type;
  _probability_type probability;





  typedef boost::shared_ptr< ::ros_tengine::FaceObject_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_tengine::FaceObject_<ContainerAllocator> const> ConstPtr;

}; // struct FaceObject_

typedef ::ros_tengine::FaceObject_<std::allocator<void> > FaceObject;

typedef boost::shared_ptr< ::ros_tengine::FaceObject > FaceObjectPtr;
typedef boost::shared_ptr< ::ros_tengine::FaceObject const> FaceObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_tengine::FaceObject_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_tengine::FaceObject_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_tengine::FaceObject_<ContainerAllocator1> & lhs, const ::ros_tengine::FaceObject_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.boundingbox == rhs.boundingbox &&
    lhs.landmark == rhs.landmark &&
    lhs.probability == rhs.probability;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_tengine::FaceObject_<ContainerAllocator1> & lhs, const ::ros_tengine::FaceObject_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_tengine

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_tengine::FaceObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_tengine::FaceObject_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_tengine::FaceObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_tengine::FaceObject_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_tengine::FaceObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_tengine::FaceObject_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_tengine::FaceObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f59aacefeb98a82d28461251a7540445";
  }

  static const char* value(const ::ros_tengine::FaceObject_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf59aacefeb98a82dULL;
  static const uint64_t static_value2 = 0x28461251a7540445ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_tengine::FaceObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_tengine/FaceObject";
  }

  static const char* value(const ::ros_tengine::FaceObject_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_tengine::FaceObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Face bounding box with marker positions\n"
"Header header\n"
"Rectangle boundingbox\n"
"Vector2D[] landmark\n"
"float32 probability\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: ros_tengine/Rectangle\n"
"# openCV style rectangle with size and 2D position\n"
"Vector2D position\n"
"Vector2D size\n"
"\n"
"================================================================================\n"
"MSG: ros_tengine/Vector2D\n"
"# simple 2D vector\n"
"float32 x\n"
"float32 y\n"
;
  }

  static const char* value(const ::ros_tengine::FaceObject_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_tengine::FaceObject_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.boundingbox);
      stream.next(m.landmark);
      stream.next(m.probability);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FaceObject_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_tengine::FaceObject_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_tengine::FaceObject_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "boundingbox: ";
    s << std::endl;
    Printer< ::ros_tengine::Rectangle_<ContainerAllocator> >::stream(s, indent + "  ", v.boundingbox);
    s << indent << "landmark[]" << std::endl;
    for (size_t i = 0; i < v.landmark.size(); ++i)
    {
      s << indent << "  landmark[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ros_tengine::Vector2D_<ContainerAllocator> >::stream(s, indent + "    ", v.landmark[i]);
    }
    s << indent << "probability: ";
    Printer<float>::stream(s, indent + "  ", v.probability);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_TENGINE_MESSAGE_FACEOBJECT_H
