# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ros_tengine/Rectangle.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import ros_tengine.msg

class Rectangle(genpy.Message):
  _md5sum = "c203b85004c7420de46fab775f4b516b"
  _type = "ros_tengine/Rectangle"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# openCV style rectangle with size and 2D position
Vector2D position
Vector2D size

================================================================================
MSG: ros_tengine/Vector2D
# simple 2D vector
float32 x
float32 y
"""
  __slots__ = ['position','size']
  _slot_types = ['ros_tengine/Vector2D','ros_tengine/Vector2D']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       position,size

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Rectangle, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.position is None:
        self.position = ros_tengine.msg.Vector2D()
      if self.size is None:
        self.size = ros_tengine.msg.Vector2D()
    else:
      self.position = ros_tengine.msg.Vector2D()
      self.size = ros_tengine.msg.Vector2D()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4f().pack(_x.position.x, _x.position.y, _x.size.x, _x.size.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = ros_tengine.msg.Vector2D()
      if self.size is None:
        self.size = ros_tengine.msg.Vector2D()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.position.x, _x.position.y, _x.size.x, _x.size.y,) = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4f().pack(_x.position.x, _x.position.y, _x.size.x, _x.size.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = ros_tengine.msg.Vector2D()
      if self.size is None:
        self.size = ros_tengine.msg.Vector2D()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.position.x, _x.position.y, _x.size.x, _x.size.y,) = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4f = None
def _get_struct_4f():
    global _struct_4f
    if _struct_4f is None:
        _struct_4f = struct.Struct("<4f")
    return _struct_4f
